version: "3.9"

services:
  db:
    image: postgres:15.2-alpine

    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - enrollment

  app:
    build: .
    restart: always
    env_file:
      - .env.docker
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - enrollment


networks:
  enrollment:
    driver: bridge